name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: llama.cpp
    provider: openai
    model: default
    apiBase: http://ramalama-qwen-service.ramalama.svc.cluster.local:8080/v1

allowAnonymousTelemetry: false
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

